# Generated by Django 4.2 on 2024-09-11 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='alimentacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='hoteleria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lavanderia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='aprobador',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ceco_id',
            field=models.ForeignKey(default='ADM01', on_delete=django.db.models.deletion.CASCADE, to='web.gerencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='web.perfiles'),
        ),
        migrations.CreateModel(
            name='MAE',
            fields=[
                ('sap', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('rut', models.CharField(default='1-9', max_length=13)),
                ('nombre', models.CharField(max_length=70)),
                ('sexo', models.CharField(default='M', max_length=1)),
                ('rol', models.CharField(blank=True, max_length=10, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('jornada', models.CharField(blank=True, max_length=10)),
                ('grupo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('correo', models.CharField(max_length=50)),
                ('ceco_id', models.ForeignKey(default='ADM01', on_delete=django.db.models.deletion.CASCADE, to='web.gerencia')),
            ],
        ),
    ]
