# Generated by Django 4.2 on 2024-09-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_area_usuario_alimentacion_usuario_hoteleria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mantencion',
            field=models.BooleanField(default=True),
        ),
    ]
