# Generated by Django 4.2 on 2024-09-16 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_usuario_mantencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edificio', models.CharField(max_length=50, unique=True)),
                ('tipo_edificio', models.CharField(choices=[('Hotel', 'Hotel'), ('Mina_Rajo', 'Mina_Rajo'), ('Taller', 'Taller'), ('Otros', 'Otros')], max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.area')),
            ],
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='areaservicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lavanderia',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SalasCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=50, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.area')),
            ],
        ),
        migrations.CreateModel(
            name='Lockers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_locker', models.PositiveIntegerField()),
                ('nombre_locker', models.CharField(max_length=5)),
                ('lugar_trabajo', models.CharField(choices=[('Saladillo', 'Saladillo'), ('SPMFC', 'SPMFC'), ('Nivel_16', 'Nivel_16'), ('Nivel_19', 'Nivel_19'), ('Concentradora', 'Concentradora'), ('Mina_Rajo', 'Mina_Rajo')], max_length=20)),
                ('casacambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.salascambio')),
                ('usuario_locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habitacion', models.CharField(max_length=50, unique=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.edificio')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
