# Generated by Django 4.2 on 2024-10-24 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('web', '0005_alter_lockers_options_alter_mae_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('en proceso', 'En Proceso'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('tipo_alojamiento', models.CharField(choices=[('parada de planta', 'Parada de Planta'), ('encierro', 'Encierro Programado'), ('contingencias', 'Contingencias'), ('permanente', 'Permanente'), ('Alojamiento por contrato', 'Alojamiento por Contrato'), ('visita', 'Visita')], default='visita', max_length=30)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('listado', models.FileField(upload_to='alojamientos')),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('ContactoId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_contacto', models.CharField(choices=[('consulta', 'Consulta'), ('felicitacion', 'Felicitación'), ('sugerencia', 'Sugerencia'), ('reclamo', 'Reclamo'), ('otro', 'Otro')], max_length=20)),
                ('emailcliente', models.EmailField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContadorSolicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_solicitudes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Movilizacion',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('en proceso', 'En Proceso'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OT',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('en proceso', 'En Proceso'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('imagen_ot', models.ImageField(blank=True, null=True, upload_to='ot')),
                ('imagen_cierre', models.ImageField(blank=True, null=True, upload_to='ot')),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('en proceso', 'En Proceso'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sobrecupo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('en proceso', 'En Proceso'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('patente', models.CharField(max_length=10)),
                ('nro_interno', models.CharField(max_length=10)),
                ('fecha_sobrecupo', models.DateTimeField(auto_now_add=True)),
                ('kilometraje', models.PositiveBigIntegerField(default=0)),
                ('motivo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('revisión técnica', 'Revisión Técnica'), ('limpieza', 'Limpieza'), ('fuera de servicio', 'Fuera de Servicio')], default='mantenimiento', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TareasMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=50, unique=True)),
                ('descripcion_tarea', models.TextField()),
                ('timing', models.PositiveBigIntegerField(default=0)),
                ('area_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.especialidad')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
            },
        ),
        migrations.RemoveField(
            model_name='historicosolicitud',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='historicosolicitud',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='itemssolicitud',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='itemssolicitud',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='areaservicio',
            options={'verbose_name': 'Area de Servicio', 'verbose_name_plural': 'Areas de Servicio'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.CharField(choices=[('dormitorio', 'Dormitorio'), ('comedor', 'Comedor'), ('oficina', 'Oficina'), ('baño', 'Baño'), ('sala de cambio', 'Sala de Cambio'), ('sala de reuniones', 'Sala de Reuniones'), ('otro', 'Otro')], default='dormitorio', max_length=50),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo_edificio',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('nodo 3500', 'Nodo 3500'), ('nodo 3700', 'Nodo 3700'), ('Taller', 'Taller'), ('Otros', 'Otros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='comentario',
            field=models.TextField(blank=True, default='Sin comentarios', null=True),
        ),
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
        migrations.DeleteModel(
            name='DetalleHistorico',
        ),
        migrations.DeleteModel(
            name='HistoricoSolicitud',
        ),
        migrations.DeleteModel(
            name='ItemsSolicitud',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
        migrations.AddField(
            model_name='sobrecupo',
            name='area_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.areaservicio'),
        ),
        migrations.AddField(
            model_name='sobrecupo',
            name='ceco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.gerencia'),
        ),
        migrations.AddField(
            model_name='sobrecupo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='area_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.areaservicio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ceco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.gerencia'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ot',
            name='area_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.areaservicio'),
        ),
        migrations.AddField(
            model_name='ot',
            name='ceco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.gerencia'),
        ),
        migrations.AddField(
            model_name='ot',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.edificio'),
        ),
        migrations.AddField(
            model_name='ot',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.habitacion'),
        ),
        migrations.AddField(
            model_name='ot',
            name='tarea_mantencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tareasmantencion'),
        ),
        migrations.AddField(
            model_name='ot',
            name='tecnico_asignado',
            field=models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='web.tecnico'),
        ),
        migrations.AddField(
            model_name='ot',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movilizacion',
            name='area_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.areaservicio'),
        ),
        migrations.AddField(
            model_name='movilizacion',
            name='ceco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.gerencia'),
        ),
        migrations.AddField(
            model_name='movilizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemscarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.servicio'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.servicio'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='area_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.areaservicio'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='ceco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.gerencia'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
