# Generated by Django 4.2 on 2024-11-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_contacto_area_contacto_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='alimentacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='hoteleria',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='lavanderia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mantencion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='transporte',
        ),
        migrations.AddField(
            model_name='areaservicio',
            name='vista',
            field=models.CharField(default='mantencion', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='servicio_autorizado',
            field=models.ManyToManyField(blank=True, to='web.areaservicio'),
        ),
    ]
