# Generated by Django 4.2 on 2024-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_usuario_alimentacion_remove_usuario_hoteleria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaservicio',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
