# Generated by Django 4.2 on 2024-11-27 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='area_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.areaservicio'),
        ),
    ]
