# Generated by Django 4.2 on 2024-11-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_carrito_area_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconosBase64',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=100)),
                ('icono_base64', models.TextField()),
            ],
        ),
    ]
